<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hotels</name>
   <tag></tag>
   <elementGuidId>baa0c3e1-d889-4bd0-b464-6ed014872380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='fadein']/header/div/div/div/div/div/div[2]/div/div/nav/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.active_hotels.waves-effect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aacd1622-d8e4-4a1b-9620-ef8932b0515c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active_hotels waves-effect</value>
      <webElementGuid>02eaa584-792e-4774-b5fd-c30cabdc742a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://phptravels.net/hotels</value>
      <webElementGuid>47af5de7-3cf0-4d25-8385-50af51586bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>hotels</value>
      <webElementGuid>c7c67078-7508-42e4-9a8c-4b8957d244ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hotels</value>
      <webElementGuid>f1caabac-1222-4bed-9f21-6d84c63f3741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@id=&quot;fadein&quot;]/header[@class=&quot;header-area&quot;]/div[@class=&quot;header-menu-wrapper padding-right-100px padding-left-100px d-flex align-items-center&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;menu-wrapper d-flex&quot;]/div[@class=&quot;main-menu-content w-100&quot;]/div[@class=&quot;align-items-center d-flex justify-content-between gap-3&quot;]/div[@class=&quot;w-100&quot;]/nav[@class=&quot;px-5&quot;]/ul[1]/li[4]/a[@class=&quot;active_hotels waves-effect&quot;]</value>
      <webElementGuid>3e22ad86-e4b4-4cdb-9600-ffeedc1642a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/header/div/div/div/div/div/div[2]/div/div/nav/ul/li[4]/a</value>
      <webElementGuid>7f552455-6e67-4b5f-a1dc-95a2fbda535c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hotels')]</value>
      <webElementGuid>33654d85-758b-4dc2-8bee-63afc74d12a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='flights'])[1]/following::a[1]</value>
      <webElementGuid>022aa8f6-fa8a-49ff-8378-bd2ebed11984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfers'])[1]/following::a[2]</value>
      <webElementGuid>d3cb26b7-da40-4e52-a096-2e2656448f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='visa'])[1]/preceding::a[1]</value>
      <webElementGuid>39c28809-b3fb-4d03-8b08-b1729db0aabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/preceding::a[2]</value>
      <webElementGuid>4ae3c21c-d693-4e0d-b7e1-63420f2d4841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hotels']/parent::*</value>
      <webElementGuid>437c99cf-1023-436a-b466-0474cdde9733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://phptravels.net/hotels')]</value>
      <webElementGuid>1bc1ef9e-c5d2-4899-a9b5-2267454bef5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>0294a4bf-b5f4-4970-a1dd-bf8605af8b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://phptravels.net/hotels' and @title = 'hotels' and (text() = 'Hotels' or . = 'Hotels')]</value>
      <webElementGuid>ee5623a5-0b3f-47ac-89b1-fbec8939b405</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
