<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChildAge_Total</name>
   <tag></tag>
   <elementGuidId>058b7803-c0cf-42b6-96c4-f84e08d83a60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='child_ages']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dropdown-item.p-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e7622a3-e380-4b36-a2b1-191ffe5e00a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item p-2</value>
      <webElementGuid>99372b5d-6b80-4c5f-9404-261728d393b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Child Age     0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16    </value>
      <webElementGuid>514c621f-fde4-4850-98f9-121e8b7bb17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;append&quot;)/li[@id=&quot;child_ages&quot;]/div[@class=&quot;dropdown-item p-2&quot;]</value>
      <webElementGuid>59ccd76e-acb5-49e4-a4a9-84a6fbc7d648</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='child_ages']/div</value>
      <webElementGuid>24cee813-b0d5-4b62-915a-c261e62203d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Child Age'])[2]/preceding::div[3]</value>
      <webElementGuid>86a70d6d-62ea-4a7b-a052-8a93fac0a382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div</value>
      <webElementGuid>d1728f82-7a5c-43a4-a4b3-3cb27e1945d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  Child Age     0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16    ' or . = '  Child Age     0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16    ')]</value>
      <webElementGuid>de67c87d-3e82-4bd7-9ad5-ad57c927deb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
