<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NextCard</name>
   <tag></tag>
   <elementGuidId>78dee930-cab5-4787-bb37-137908dd85ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='fadein']/section[2]/div/div[2]/div/div/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.owl-next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d23ebf4b-4f63-48b7-b712-a411b4ebf219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>owl-next</value>
      <webElementGuid>57a3748b-af22-4a85-af64-e2db69a35028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@id=&quot;fadein&quot;]/section[@class=&quot;hotel-area section-bg section-padding overflow-hidden padding-right-100px padding-left-100px bg-light&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row padding-top-50px&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;hotel-card-wrap&quot;]/div[@class=&quot;hotel-card-carousel carousel-action owl-loaded owl-carousel&quot;]/div[@class=&quot;owl-nav&quot;]/div[@class=&quot;owl-next&quot;]</value>
      <webElementGuid>2c62e149-29fb-48ab-a6bc-b30b670d4501</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/section[2]/div/div[2]/div/div/div/div[2]/div[2]</value>
      <webElementGuid>4e27df8a-83cb-4f9f-817e-2bc0be995f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[19]/following::div[3]</value>
      <webElementGuid>59df0611-d8da-42de-8d68-59379f1791c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need Help? Contact us'])[1]/preceding::div[6]</value>
      <webElementGuid>90a9f742-baf9-4edd-b626-6efcd5c62ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secure Payments'])[1]/preceding::div[9]</value>
      <webElementGuid>27a526f7-8587-4694-8d53-d9ea22d4c613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div[2]</value>
      <webElementGuid>49875ebe-f0d3-42ff-a201-5a6d73f7b070</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
