<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PreviousCard</name>
   <tag></tag>
   <elementGuidId>981926b5-3467-42d3-8dee-0aa28b69dae3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='fadein']/section[2]/div/div[2]/div/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.owl-prev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3e01575b-faf0-45de-b2eb-1de1691b35c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>owl-prev</value>
      <webElementGuid>5c08ab3d-6a66-41c1-928e-fcd5fac618ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@id=&quot;fadein&quot;]/section[@class=&quot;hotel-area section-bg section-padding overflow-hidden padding-right-100px padding-left-100px bg-light&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row padding-top-50px&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;hotel-card-wrap&quot;]/div[@class=&quot;hotel-card-carousel carousel-action owl-loaded owl-carousel&quot;]/div[@class=&quot;owl-nav&quot;]/div[@class=&quot;owl-prev&quot;]</value>
      <webElementGuid>250e1541-c5df-4146-9f85-7e24a0478491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/section[2]/div/div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>d8933fcc-4c92-4c48-bc94-7f261ecdc0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[19]/following::div[2]</value>
      <webElementGuid>c0259012-a837-43dd-8ee9-5d39c4e60564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need Help? Contact us'])[1]/preceding::div[7]</value>
      <webElementGuid>05419858-a3da-4d5c-8c79-7c09a73d1807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secure Payments'])[1]/preceding::div[10]</value>
      <webElementGuid>5e10a895-c023-42a7-a7e6-d120b495ad48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>66523118-6b49-4c58-9fb7-bad0ece3f059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
