<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Childs_Plus</name>
   <tag></tag>
   <elementGuidId>504357a3-e930-43e4-804b-63c0f53356f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='hotels-search']/div/div/div[3]/div/div/div/div/div[3]/div/div/div[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.qtyBtn.d-flex.align-items-center.child_ages > div.qtyInc > i.la.la-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ba74213e-b154-4b26-9b85-691f2eaacc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>la la-plus</value>
      <webElementGuid>29c7255d-8fa6-4b30-802a-e487489f3cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hotels-search&quot;)/div[@class=&quot;main_search contact-form-action&quot;]/div[@class=&quot;row g-1&quot;]/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;input-box&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;dropdown dropdown-contain&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-wrap&quot;]/div[@class=&quot;dropdown-item&quot;]/div[@class=&quot;qty-box d-flex align-items-center justify-content-between&quot;]/div[@class=&quot;qtyBtn d-flex align-items-center child_ages&quot;]/div[@class=&quot;qtyInc&quot;]/i[@class=&quot;la la-plus&quot;]</value>
      <webElementGuid>9471357c-0171-4e0d-a110-e699823cd656</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hotels-search']/div/div/div[3]/div/div/div/div/div[3]/div/div/div[2]/i</value>
      <webElementGuid>9fedeb78-bfb4-4e12-a959-d4620645a92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/i</value>
      <webElementGuid>dff5e889-0f9e-4623-93ac-151d4409762d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
