<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Number_Childs</name>
   <tag></tag>
   <elementGuidId>58282190-bfb5-49e2-a9f2-6668e65c1114</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'childs' and @id = 'childs']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='childs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#childs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbda585b-b5ee-4787-a330-5539791cb7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9695a3c0-b751-4442-9c6e-f499b9dbf0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>childs</value>
      <webElementGuid>69beaa09-bb3e-4765-8b5d-c7b162eb8fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>childs</value>
      <webElementGuid>78f20fd8-96c0-458f-aabb-419e95b503c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cbcd189d-32ca-413d-a803-51e836736b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qtyInput_hotels</value>
      <webElementGuid>8749ca68-4f47-4fad-ba05-8e4c09f2b008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;childs&quot;)</value>
      <webElementGuid>51935379-fd5a-45ad-bbfe-51f197b4067f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='childs']</value>
      <webElementGuid>07d36a55-8654-4233-a4f8-758d18c8a784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hotels-search']/div/div/div[3]/div/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>f7aaaa9f-3de4-4794-a674-903c36d003b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>2715bccd-8c39-4266-bf48-e5ed7402965a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'childs' and @id = 'childs']</value>
      <webElementGuid>7cc6c952-214b-4c4b-943b-cf725ee67aa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
