<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Number_Room</name>
   <tag></tag>
   <elementGuidId>c8402652-75bf-498b-a637-e144dd26d544</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'roomInput' and @id = 'rooms']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rooms']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rooms</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7805c13-1e18-465e-b3f3-793f0239be5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b0bee51-c9af-45b6-989d-9145be942f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>roomInput</value>
      <webElementGuid>3367f697-f47e-4f97-98f0-00954e1d5424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rooms</value>
      <webElementGuid>0089aecf-ca42-46db-8e3f-6af0f1f5f282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>44590e3a-82a8-4bd8-b021-ead091d77c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rooms&quot;)</value>
      <webElementGuid>8c1d58c7-8b59-4976-ba52-371ca76de7f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rooms']</value>
      <webElementGuid>5d122d0a-448d-4547-b819-11a6810c5452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hotels-search']/div/div/div[3]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>c74cc82a-7a9a-404c-a834-03fac1854dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/input</value>
      <webElementGuid>51b34202-0015-4429-875f-2fd6eb39d8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'roomInput' and @id = 'rooms']</value>
      <webElementGuid>fdca4630-28da-465b-8e80-101eba82c7fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
