<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Number_Adults</name>
   <tag></tag>
   <elementGuidId>b4f6d24d-e56c-4957-abba-f1d7b438c7cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'adults' and @id = 'adults']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='adults']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#adults</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d0037d8-3884-4944-9a3e-2ad9c27704b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>225cc539-df27-4bfe-b6cd-68b70d5a37d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adults</value>
      <webElementGuid>2ad0e725-e634-4be0-bd73-b343a285d567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adults</value>
      <webElementGuid>9d526943-e914-46f7-9972-e41a13cbf4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>55a23623-4ba2-4f8a-85d3-ddc44996939b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qtyInput_hotels</value>
      <webElementGuid>c62053ec-2cd8-4aff-a0ad-c245e398a819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adults&quot;)</value>
      <webElementGuid>16105780-e909-4dc8-bd1a-8818b5ade2b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='adults']</value>
      <webElementGuid>5de077c1-861d-4277-a000-944336c1caff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hotels-search']/div/div/div[3]/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>9aa60724-37fd-44b2-8bbb-27b60b6c1904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>38e4d1ba-5f15-4891-8ffc-49516b05b406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'adults' and @id = 'adults']</value>
      <webElementGuid>3bf5602e-34b8-49c8-b0cd-b6a7985a2865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
