<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rooms_Plus</name>
   <tag></tag>
   <elementGuidId>fb739461-d459-4bf5-b8f1-22d9a83f4a44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='hotels-search']/div/div/div[3]/div/div/div/div/div/div/div/div[3]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.la.la-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a473999c-bcf9-44ee-b2af-d3e7f8af1730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>la la-plus</value>
      <webElementGuid>3ea9b504-a2db-49b9-b8f8-cbab3dab1c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hotels-search&quot;)/div[@class=&quot;main_search contact-form-action&quot;]/div[@class=&quot;row g-1&quot;]/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;input-box&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;dropdown dropdown-contain&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-wrap&quot;]/div[@class=&quot;dropdown-item&quot;]/div[@class=&quot;roomBtn d-flex align-items-center justify-content-between&quot;]/div[@class=&quot;qtyBtn d-flex align-items-center&quot;]/div[@class=&quot;roomInc&quot;]/i[@class=&quot;la la-plus&quot;]</value>
      <webElementGuid>fb300ccb-596b-4b31-8085-f3187b3fc981</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hotels-search']/div/div/div[3]/div/div/div/div/div/div/div/div[3]/i</value>
      <webElementGuid>7c53911c-794c-44ac-8fb2-59190fc86f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/i</value>
      <webElementGuid>d5733957-7cf1-4964-b2ce-53283448ced8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
