<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkin_Checkout</name>
   <tag></tag>
   <elementGuidId>e5345960-0b03-4275-9638-dc08f4a9e15a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[@id='fadein']/section/div/div/div/div/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='fadein']/section/div/div/div/div/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>17e59737-7cf9-493e-a746-5e6f90de04fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Nights ( 20-10-2022 - 21-10-2022 )</value>
      <webElementGuid>cfc23fcb-f2cd-46cc-bbdd-97a6d7c0b0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[@id='fadein']/section/div/div/div/div/div/div/div/div/p</value>
      <webElementGuid>48906e9a-175f-4015-842f-f651f0cc3651</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/section/div/div/div/div/div/div/div/div/p</value>
      <webElementGuid>5fba4129-b2ec-4266-9d95-f380b1b3abeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Hotels in dubai'])[1]/following::p[1]</value>
      <webElementGuid>4f2a6c23-c0f3-479f-9ce8-e1eb5a6fe091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier Login'])[1]/following::p[1]</value>
      <webElementGuid>be4b98ea-6c44-42ba-9b8d-15b546a7f0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modify Search'])[1]/preceding::p[2]</value>
      <webElementGuid>ddb4d49d-3834-4377-84f9-5ba917e5e2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='( 20-10-2022 - 21-10-2022 )']/parent::*</value>
      <webElementGuid>786b418c-d38d-4081-a139-1016f152a989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>d5fe8a7e-0f6e-40f0-8a6a-4b00b064a0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '1 Nights ( 20-10-2022 - 21-10-2022 )' or . = '1 Nights ( 20-10-2022 - 21-10-2022 )')]</value>
      <webElementGuid>8fea91c0-3e5d-425b-a1f4-254bd2995a80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
